/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import conexion.BaseDeDatosConexion;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 52953
 */
public class BusquedaAlojamiento extends javax.swing.JFrame {
    //Conexion a la base de datos
    PreparedStatement ps=null;
    ResultSet rs=null;
    BaseDeDatosConexion con=new BaseDeDatosConexion();
    Connection conn=con.getConection();
    DefaultTableModel modelo;
    
    public BusquedaAlojamiento() {
       initComponents();
       //llamada al metodo que muestra en la pantalla de inicio todos los alojamientos disponible en orden de puntaje descendente
       muestraAlojamientosPuntaje();
       //oculta jtextfield que guarda un id, o una entidad el cual se ocupa para realizar una busqueda
       txtIdAl.setVisible(false);
       ciudadBase.setVisible(false);  
    }

        //metodo que muestra todos los alojamientos
        public void muestraAlojamientosPuntaje(){
        modelo = new DefaultTableModel();
        File archivo;
        try{
            DefaultTableModel modelo =new DefaultTableModel();
            tablaAlojamientoss.setModel(modelo);
            BaseDeDatosConexion con=new BaseDeDatosConexion();
            Connection conn=con.getConection();
            //Consulta sql que muestra en orden descendente los alojamientos existentes
            ps=conn.prepareStatement("SELECT id_alojamiento,titulo,entidad,puntaje FROM alojamiento order by puntaje desc");
            rs=ps.executeQuery();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantColumnas=rsMd.getColumnCount();
            //crea las colunas y les da un titulo
            modelo.addColumn("Id_Alojamiento");
            modelo.addColumn("Titulo");
            modelo.addColumn("entidad");
            modelo.addColumn("puntaje");
            //modelo.addColumn("Imagen");
            this.tablaAlojamientoss.setModel(modelo);
            while(rs.next()){
                Object[] filas=new Object[18];
                //ciclo que muestra los datos de la base de datos obtenidos, de acuerdo al orden establecido
                for(int i=0; i<cantColumnas; i++){
                    filas[i]=rs.getObject(i+1);
                }    
                modelo.addRow(filas);
            }
        }
        catch(SQLException exp){
            System.err.println(exp.toString());
        }
    }
               
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo2.jpg"));
        return retValue;
    }
    
    /*
    void muestraImagenes(){
        Image img=null;
        ImageIcon imagen=null;
        DefaultListModel lista = new DefaultListModel();
        try{
            BaseDeDatosConexion con=new BaseDeDatosConexion();
            Connection conn=con.getConection();
            ps=conn.prepareStatement("SELECT imagen FROM alojamiento");   
            rs=ps.executeQuery();
            while(rs.next()){
                Blob fotos=rs.getBlob("imagen");
                if(fotos!=null){
                    byte[] recupera=fotos.getBytes(1,(int)fotos.length());
                    BufferedImage imagenes= ImageIO.read(new ByteArrayInputStream(recupera));
                    img=imagenes.getScaledInstance(50,50,Image.SCALE_SMOOTH);
                    imagen=new ImageIcon(img);
                }else{
                    imagen=new ImageIcon(getClass().getResource("/imagenes/casa9.jpg")); 
                }
                lista.addElement(imagen);
            }
          //  this.jLista1.setModel(lista);
        }catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(null,"No existe el usuario");
       } catch (IOException ex) { 
            Logger.getLogger(BusquedaAlojamiento.class.getName()).log(Level.SEVERE, null, ex);
        } 
    } */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonInicio = new javax.swing.JButton();
        botonRegistrate = new javax.swing.JButton();
        botonIS = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        GuardaCiudad = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAlojamientoss = new javax.swing.JTable();
        txtIdAl = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ciudadBase = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonInicio.setBackground(new java.awt.Color(0, 153, 153));
        botonInicio.setText("Inicio");
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioMouseClicked(evt);
            }
        });
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 100, 40));

        botonRegistrate.setBackground(new java.awt.Color(0, 153, 153));
        botonRegistrate.setText("Registrate");
        botonRegistrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrateMouseClicked(evt);
            }
        });
        botonRegistrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrateActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 110, 40));

        botonIS.setBackground(new java.awt.Color(0, 153, 153));
        botonIS.setText("Iniciar Sesion");
        botonIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonISMouseClicked(evt);
            }
        });
        botonIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonISActionPerformed(evt);
            }
        });
        getContentPane().add(botonIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 120, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo2.jpg"))); // NOI18N
        logo.setText("jLabel1");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 140));

        buscar.setBackground(new java.awt.Color(0, 153, 153));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 80, 90, 30));
        getContentPane().add(GuardaCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 80, 140, 30));

        jTextField1.setBackground(new java.awt.Color(102, 204, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setText("    UNIRENTA");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t.jpg"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 70, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/f.jpg"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 70, 70));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i.jpg"))); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 70, 70));

        salir.setBackground(new java.awt.Color(0, 153, 153));
        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 90, 40));

        tablaAlojamientoss.setBackground(new java.awt.Color(204, 153, 255));
        tablaAlojamientoss.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 153)));
        tablaAlojamientoss.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        tablaAlojamientoss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tablaAlojamientoss.setEditingColumn(0);
        tablaAlojamientoss.setEditingRow(0);
        tablaAlojamientoss.setSelectionBackground(new java.awt.Color(153, 0, 255));
        tablaAlojamientoss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlojamientossMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaAlojamientoss);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 790, 250));
        getContentPane().add(txtIdAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 60, -1));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setText("Ver mas detalles");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, 210, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa9.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 360, 210, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa3.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 500, 210, 120));
        getContentPane().add(ciudadBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 140, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backGround.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
       //boton que nos lleva al inicio de la aplicacion
       BusquedaAlojamiento index = new BusquedaAlojamiento();
       index.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_botonInicioActionPerformed

    private void botonRegistrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrateActionPerformed
       //boton que nos lleva al menu de registro de la de la aplicacion
       RegistroNuevo mr= new RegistroNuevo();
       mr.setVisible(true);
       this.dispose();     
    }//GEN-LAST:event_botonRegistrateActionPerformed

    private void botonISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonISActionPerformed
       //boton que nos manda a la ventana menú inicio de sesion (Estudiante/Arrendatario)
       MenuIS menuis= new MenuIS();
       menuis.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_botonISActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        //guarda en varible string la entidad ingresada para la busqueda
        String d=GuardaCiudad.getText();
        //llamada a funcion que nos devuelve un 1 si hay al menos un alojamiento para en tal entidad
        int encuentra=existe(d);
        System.out.println("esto retorna la funcion: "+encuentra);
        if(encuentra==1){
        BusquedaAlojamientos();        
        }
    }//GEN-LAST:event_buscarActionPerformed
    
    //metodo que devuelve 1 si existe un alojamiento en la ciudad ingresada en el jtextfield de busqueda    
    public int existe(String ciudad){
        Integer result=0;
        try{
            Statement ejecutor=conn.createStatement();
            //consulta sql que selecciona la entidad de la base de datos cuando la entidad es igual a la ingresada en el campo de busqueda
            ResultSet rs=ejecutor.executeQuery("SELECT entidad FROM alojamiento WHERE entidad='"+ciudad+"'");
            if(rs.next()){
                ciudadBase.setText(rs.getString("entidad"));  //Guarda la entidad
                String ciudadEnBase=ciudadBase.getText();
                System.out.println("esto tiene ciudad ingresada:"+ciudad);
                System.out.println("esto tiene base de datos:"+ciudadEnBase);                     
                //compara las cadenas y si son iguales entonces retorna un 1
                if(ciudad.equals(ciudadEnBase)){
                    result=1;
               }else{//si no son iguales retorna un 0 entonces no hay alojamientos en esa entidad
                   System.out.println("entra aqui:"+ciudad);
                   result=0;
               }    
            }else{
                JOptionPane.showMessageDialog(null,"No existen alojamientos para esta entidad federativa");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al conectar"+e.getMessage(),e.getMessage(),JOptionPane.ERROR_MESSAGE);
        }
        return result;
    }
        //metodo que busca y muestra todos los alojamientos de una misma entidad 
        public void BusquedaAlojamientos(){
        modelo = new DefaultTableModel();
        File archivo;
        try{
            DefaultTableModel modelo =new DefaultTableModel();
            tablaAlojamientoss.setModel(modelo);
            BaseDeDatosConexion con=new BaseDeDatosConexion();
            Connection conn=con.getConection();
            //Consulta que encuentra todos los alojamientos con entidad igual a la buscada
            ps=conn.prepareStatement("SELECT id_alojamiento,titulo,entidad,puntaje FROM alojamiento WHERE entidad=?");
            //String ciudad=RecibeCiudad.getText(); 
            ps.setString(1,GuardaCiudad.getText());
            rs=ps.executeQuery();
                ResultSetMetaData rsMd = rs.getMetaData();
                int cantColumnas=rsMd.getColumnCount();
                //crea las columnas en la tabla y les da titulo
                modelo.addColumn("Id_Alojamiento");
                modelo.addColumn("Titulo");
                modelo.addColumn("entidad");
                modelo.addColumn("puntaje");
                //modelo.addColumn("Imagen");
                this.tablaAlojamientoss.setModel(modelo);
                while(rs.next()){
                    Object[] filas=new Object[18];
                    //for(int i=0; i<cantColumnas-1; i++){
                        //asiga a cada fila los campos correspondientes de acuerdo a la consulta
                        filas[0]=rs.getObject(1);
                        filas[1]=rs.getObject(2);
                        filas[2]=rs.getObject(3);
                        filas[3]=rs.getObject(4);
                    modelo.addRow(filas);
            }
        }catch(SQLException exp){
            System.err.println(exp.toString());
        }
    } 
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void botonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseClicked
     
    }//GEN-LAST:event_botonInicioMouseClicked

    private void botonRegistrateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrateMouseClicked
    
    }//GEN-LAST:event_botonRegistrateMouseClicked

    private void botonISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonISMouseClicked
      
    }//GEN-LAST:event_botonISMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void tablaAlojamientossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlojamientossMouseClicked
       //selecciona una fila tras dar click sobre ella y guarda el id del alojamiento
       int select = tablaAlojamientoss.rowAtPoint(evt.getPoint());
       txtIdAl.setText(String.valueOf(tablaAlojamientoss.getValueAt(select,0)));
    }//GEN-LAST:event_tablaAlojamientossMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //boton que manda a la siguiente ventana donde se pueden ver los detalles del alojamiento 
        //seleccionado anteriormente
        ReservaAlojamiento res= new ReservaAlojamiento();
        res.setVisible(true);
        this.dispose();
        res.guardaIdAl.setText(txtIdAl.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaAlojamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaAlojamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaAlojamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaAlojamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaAlojamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GuardaCiudad;
    private javax.swing.JButton botonIS;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonRegistrate;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField ciudadBase;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaAlojamientoss;
    private javax.swing.JTextField txtIdAl;
    // End of variables declaration//GEN-END:variables
}
