/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import conexion.BaseDeDatosConexion;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 52953
 */
public class CRUDAlojamiento extends javax.swing.JFrame {
    //Conexion a la base de datos en PhpMyAdmin
    PreparedStatement ps=null;
    ResultSet rs=null;
    BaseDeDatosConexion con=new BaseDeDatosConexion();
    Connection conn=con.getConection();
    DefaultTableModel modelo;
    
    public CRUDAlojamiento() {
        initComponents();
        mostrar();    
        //oculta un jtextfield que guarda un id
        recibeIdArr2.setVisible(false);
    }
    
    public void mostrar(){
        //tabla en la que se muestran los datos del alojamiento
        modelo=new DefaultTableModel();
        File archivo;
        try{
            DefaultTableModel modelo =new DefaultTableModel();
            tablaAlojamiento.setModel(modelo);
            
            BaseDeDatosConexion con=new BaseDeDatosConexion();
            Connection conn=con.getConection();
            //Consulta sql que selecciona los campos de todos los alojamientos de acuerdo al arrendador_id
            ps=conn.prepareStatement("SELECT id_alojamiento, titulo, entidad, municipio, cp, dir, numHabs, costo, servicios, tipo, detalles, arrendador_id, disponibilidad,imagen FROM alojamiento WHERE arrendador_id = ?");
            //int ide=Integer.parseInt(recibeIdArr.getText());
            //ps.setInt(1,ide);
            String id=recibeIdArr2.getText(); 
            ps.setString(1,id);
            rs=ps.executeQuery();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantColumnas=rsMd.getColumnCount();
            //Crea columnas con titulo
            modelo.addColumn("Id_Alojamiento");
            modelo.addColumn("Titulo");
            modelo.addColumn("Entidad_Federativa");
            modelo.addColumn("Ciudad_Municipio");
            modelo.addColumn("Codigo_Postal");
            modelo.addColumn("Direccion");
            modelo.addColumn("Num_Habitaciones");
            modelo.addColumn("Costo");
            modelo.addColumn("Servicios");
            modelo.addColumn("Tipo");
            modelo.addColumn("Detalles");
            modelo.addColumn("arrendador_id");
            modelo.addColumn("Disponibilidad");
            modelo.addColumn("Imagen");
            this.tablaAlojamiento.setModel(modelo);
            
            while(rs.next()){
                Object[] filas=new Object[cantColumnas];
                //for(int i=0; i<cantColumnas-1; i++){
                //Muestra todas las filas con cada detalle de alojamientos
                    filas[0]=rs.getObject(1);
                    filas[1]=rs.getObject(2);
                    filas[2]=rs.getObject(3);
                    filas[3]=rs.getObject(4);
                    filas[4]=rs.getObject(5);
                    filas[5]=rs.getObject(6);
                    filas[6]=rs.getObject(7);
                    filas[7]=rs.getObject(8);
                    filas[8]=rs.getObject(9);
                    filas[9]=rs.getObject(10);
                    filas[10]=rs.getObject(11);
                    filas[11]=rs.getObject(12);
                    filas[12]=rs.getObject(13);
                    filas[13]=rs.getObject(14);
                modelo.addRow(filas);
            }
        }
        catch(SQLException exp){
            System.err.println(exp.toString());
        }
    }
    //metodo que limpia los campos despues de realizar alguna acción.
     private void limpiar(){
        txtTitulo.setText(null); 
        txtEntidad.setText(null);
        txtCiudad.setText(null);
        txtCP.setText(null);
        txtDir.setText(null);
        txtNumHabs.setText(null);
        txtCosto.setText(null);
        txtServicios.setText(null);
        txtTipo.setText(null);
        txtDetalles.setText(null);
        txtDisp.setText(null);
        txtImagen.setText(null);
        idMod.setText(null);
        idAl.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        recibeIdArr2 = new javax.swing.JTextField();
        entidad = new javax.swing.JLabel();
        ciudad = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEntidad = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtCP = new javax.swing.JTextField();
        txtNumHabs = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtServicios = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDir = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAlojamiento = new javax.swing.JTable();
        idAl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idMod = new javax.swing.JTextField();
        mostrar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDisp = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        txtImagen = new javax.swing.JTextField();
        botonImagen = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo2.jpg"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 150, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 204, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setText("     UNIRENTA");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 150, 30));

        btnVolver.setBackground(new java.awt.Color(0, 153, 153));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 70, 30));

        btnInsertar.setBackground(new java.awt.Color(0, 204, 204));
        btnInsertar.setText("Insertar Nuevo");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 130, 30));

        btnModificar.setBackground(new java.awt.Color(0, 153, 153));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 90, 30));

        btnEliminar.setBackground(new java.awt.Color(0, 204, 204));
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 400, 90, 30));

        recibeIdArr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recibeIdArr2ActionPerformed(evt);
            }
        });
        getContentPane().add(recibeIdArr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 80, 30));

        entidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        entidad.setForeground(new java.awt.Color(204, 51, 0));
        entidad.setText("Entidad Federativa:");
        getContentPane().add(entidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, 20));

        ciudad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ciudad.setForeground(new java.awt.Color(204, 51, 0));
        ciudad.setText("Ciudad o municipio:");
        getContentPane().add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setText("Codigo Postal:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 51, 0));
        jLabel4.setText("Direccion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 51, 0));
        jLabel5.setText("# de habitaciones:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 51, 0));
        jLabel6.setText("Costo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 51, 0));
        jLabel7.setText("Servicios:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setText("Tipo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 51, 0));
        jLabel10.setText("Detalles:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 160, -1, -1));

        txtEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 250, -1));
        getContentPane().add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 250, -1));
        getContentPane().add(txtCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 100, -1));
        getContentPane().add(txtNumHabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 60, -1));
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 100, -1));
        getContentPane().add(txtServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 400, -1));

        txtDir.setColumns(20);
        txtDir.setRows(5);
        jScrollPane1.setViewportView(txtDir);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 180, 90));

        tablaAlojamiento.setBackground(new java.awt.Color(204, 153, 255));
        tablaAlojamiento.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        tablaAlojamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Alojamiento", "Entidad federativa", "Ciudad o municipio", "Codigo postal", "Direccion", "Numero de Habitaciones", "Costo", "Servicios", "Tipo", "Incluye", "Detalles", "Arrendador Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaAlojamiento.setSelectionBackground(new java.awt.Color(153, 0, 255));
        jScrollPane2.setViewportView(tablaAlojamiento);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 1240, 200));

        idAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAlActionPerformed(evt);
            }
        });
        getContentPane().add(idAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 400, 90, 30));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Ingrese el id_Alojamiento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 240, 30));

        btnGuardar.setBackground(new java.awt.Color(0, 153, 153));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 100, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Realice los cambios y presione guardar  ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 350, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Ingrese el id_Alojamiento");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 230, 30));

        idMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idModActionPerformed(evt);
            }
        });
        getContentPane().add(idMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 80, 30));

        mostrar.setBackground(new java.awt.Color(0, 204, 204));
        mostrar.setText("Mostrar lista de alojamientos");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 200, 30));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Rellene los siguientes campos para insertar un nuevo alojamiento");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 610, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 51, 0));
        jLabel13.setText("Titulo:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 50, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 250, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 51, 0));
        jLabel14.setText("Disponible:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, -1, -1));
        getContentPane().add(txtDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 100, -1));
        getContentPane().add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 110, -1));

        txtDetalles.setColumns(20);
        txtDetalles.setRows(5);
        jScrollPane3.setViewportView(txtDetalles);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 130, 130, 80));
        getContentPane().add(txtImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 240, 180, -1));

        botonImagen.setBackground(new java.awt.Color(204, 51, 0));
        botonImagen.setText("Imagen");
        botonImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImagenActionPerformed(evt);
            }
        });
        getContentPane().add(botonImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 240, -1, -1));

        fondo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backGround.jpg"))); // NOI18N
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 782));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       //Nos regresa a la ventana anterio (menu arrendador)
       MenuArrendador mu = new  MenuArrendador();
       //Envia el id de vuelta para que no se pierda
       mu.recibeIdArr.setText(recibeIdArr2.getText());
       mu.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try{
            BaseDeDatosConexion objCon=new BaseDeDatosConexion();
            Connection conn=objCon.getConection();     
            //Consulta sql donde inserta un nuevo alojamiento con todos sus campos de acuerdo al arrendador_id
            ps=conn.prepareStatement("INSERT INTO alojamiento( titulo,entidad,municipio,cp,dir,numHabs,costo,servicios,tipo,detalles,arrendador_id,disponibilidad,imagen) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)"); 
            ps.setString(1,txtTitulo.getText());
            ps.setString(2,txtEntidad.getText());
            ps.setString(3,txtCiudad.getText());
            ps.setString(4,txtCP.getText());
            ps.setString(5,txtDir.getText());
            ps.setString(6,txtNumHabs.getText());
            ps.setString(7,txtCosto.getText());
            ps.setString(8,txtServicios.getText());
            ps.setString(9,txtTipo.getText());
            ps.setString(10,txtDetalles.getText());
            ps.setInt(11,Integer.parseInt(recibeIdArr2.getText()));
            ps.setString(12,txtDisp.getText());
            ps.setString(13,txtImagen.getText());
            
            int res=ps.executeUpdate();
            if(res>0){
                JOptionPane.showMessageDialog(null, "Datos de alojamiento guardados");
                limpiar();
                mostrar(); 
            }else{
                JOptionPane.showMessageDialog(null, "Error al guardar datos");
            }
            conn.close();
        }
        catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente");
        } 
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        try{
            BaseDeDatosConexion con=new BaseDeDatosConexion();
            Connection conn=con.getConection();
            //Consulta sql que selecciona todos los campos de la tabla alojamiento de acuerdo al id_alojamiento
            ps=conn.prepareStatement("SELECT * FROM alojamiento WHERE id_alojamiento = ?");
            int ide=Integer.parseInt(idMod.getText());
            ps.setInt(1,ide);
            rs=ps.executeQuery();
            if(rs.next()){               
                //Muestra en cada jtextfield los datos recibidos de la base de datos para posteriormente ser modificados y gusardados
                txtTitulo.setText(rs.getString("titulo"));
                txtEntidad.setText(rs.getString("entidad"));
                txtCiudad.setText(rs.getString("municipio"));
                txtCP.setText(rs.getString("cp"));
                txtDir.setText(rs.getString("dir"));
                txtNumHabs.setText(rs.getString("numHabs"));
                txtCosto.setText(rs.getString("costo"));
                txtServicios.setText(rs.getString("servicios"));
                txtTipo.setText(rs.getString("tipo"));
                txtDetalles.setText(rs.getString("detalles"));
                recibeIdArr2.setText(rs.getString("arrendador_id")); 
                txtDisp.setText(rs.getString("disponibilidad")); 
                txtImagen.setText(rs.getString("imagen")); 
                //Muestra los datos en la tabla
                mostrar();
            }else{
                JOptionPane.showMessageDialog(null,"No existe el usuario");
                mostrar();
            }
             //Cierra la conexion
             conn.close();
        }catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(null,"No existe el usuario");
        }
    }//GEN-LAST:event_btnModificarActionPerformed


    private void txtEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntidadActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    
        try{
            BaseDeDatosConexion con=new BaseDeDatosConexion();
            Connection conn=con.getConection();
            //Consulta sql que elimina un alojamiento de acuerdo al id_alojamiento ingresado
            ps=conn.prepareStatement("DELETE FROM alojamiento WHERE id_alojamiento=?");
            ps.setInt(1,Integer.parseInt(idAl.getText()));            
            int res=ps.executeUpdate();            
            if(res>0){
                JOptionPane.showMessageDialog(null, "Alojamiento eliminado");
                //muestra la tabla de alojamientos despues de eliminar uno.
                mostrar();
                limpiar();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar alojamiento");
                mostrar();
                limpiar();
            }
        //Cierra la conexion.    
        conn.close();
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null,"Ingrese un id correcto");
        }    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void idAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAlActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        PreparedStatement ps=null;
        ResultSet rs=null;
        try{
            BaseDeDatosConexion objCon=new BaseDeDatosConexion();
            Connection conn=objCon.getConection();  
            //Consulta sql que guarda cambios realizados en algun alojamiento de acuerdo al id_alojamiento
            ps=conn.prepareStatement("UPDATE alojamiento SET titulo=?, entidad=?,municipio=?,cp=?,dir=?,numHabs=?,costo=?,servicios=?,tipo=?,detalles=?,arrendador_id=?, disponibilidad=?,imagen=? WHERE id_alojamiento=?"); 
            ps.setString(1,txtTitulo.getText());
            ps.setString(2,txtEntidad.getText());
            ps.setString(3,txtCiudad.getText());
            ps.setString(4,txtCP.getText());
            ps.setString(5,txtDir.getText());
            ps.setString(6,txtNumHabs.getText());
            ps.setString(7,txtCosto.getText());
            ps.setString(8,txtServicios.getText());
            ps.setString(9,txtTipo.getText());
            ps.setString(10,txtDetalles.getText());
            ps.setInt(11,Integer.parseInt(recibeIdArr2.getText()));
            ps.setString(12,txtDisp.getText());
            ps.setString(13,txtImagen.getText());
            ps.setInt(14,Integer.parseInt(idMod.getText())); 
            int res=ps.executeUpdate();
            //muestra los datos modificadoe
            mostrar();  
            if(res>0){
                JOptionPane.showMessageDialog(null, "Datos modificados correctamente");
                limpiar();
            }else{
                JOptionPane.showMessageDialog(null, "Error al guardar datos");
                limpiar();
            }
            //Cierra la conexion
            conn.close();
        }
        catch(HeadlessException | SQLException e){
           System.err.print(e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void idModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idModActionPerformed

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void recibeIdArr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recibeIdArr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recibeIdArr2ActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        mostrar();
    }//GEN-LAST:event_mostrarActionPerformed

    private void botonImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImagenActionPerformed
        //Abre una ventana para seleccionar imagen local para poder guardarla en la base de datos
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
        j.setFileFilter(fil);
        
        int s = j.showOpenDialog(this);
        if(s == JFileChooser.APPROVE_OPTION){
            String ruta = j.getSelectedFile().getAbsolutePath();
            txtImagen.setText(ruta);
        }
    }//GEN-LAST:event_botonImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDAlojamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDAlojamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDAlojamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDAlojamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDAlojamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonImagen;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel ciudad;
    private javax.swing.JLabel entidad;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField idAl;
    private javax.swing.JTextField idMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton mostrar;
    public static javax.swing.JTextField recibeIdArr2;
    private javax.swing.JTable tablaAlojamiento;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextArea txtDetalles;
    private javax.swing.JTextArea txtDir;
    private javax.swing.JTextField txtDisp;
    private javax.swing.JTextField txtEntidad;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNumHabs;
    private javax.swing.JTextField txtServicios;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
