/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import conexion.BaseDeDatosConexion;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author 52953
 */
public class FinalizarReservaPago extends javax.swing.JFrame {
    //conexion a la base de datos
    PreparedStatement ps=null;
    ResultSet rs=null;
    BaseDeDatosConexion con=new BaseDeDatosConexion();
    Connection conn=con.getConection(); 
    
    public FinalizarReservaPago() {
        initComponents();
        //oculta jtextfield que guarda el identificador tanto del estudiante como del alojamiento que reservará
        guardaIdAl.setVisible(false);
        guardaIdEst.setVisible(false);
    }
    
     public Image getIconImage(){
        //logotipo de la aplicacion
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo2.jpg"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        unirenta = new javax.swing.JTextField();
        inicio = new javax.swing.JButton();
        pagar = new javax.swing.JButton();
        inst = new javax.swing.JButton();
        fb = new javax.swing.JButton();
        tw = new javax.swing.JButton();
        bienvfin = new javax.swing.JLabel();
        targeta = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        numTargeta = new javax.swing.JTextField();
        titularTargeta = new javax.swing.JTextField();
        fechaVence = new javax.swing.JTextField();
        volver = new javax.swing.JButton();
        guardaIdEst = new javax.swing.JTextField();
        guardaIdAl = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        codigoSeguridad = new javax.swing.JTextField();
        codigoReserva = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo2.jpg"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 150, -1));

        unirenta.setBackground(new java.awt.Color(102, 204, 0));
        unirenta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        unirenta.setText("     UNIRENTA");
        getContentPane().add(unirenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 150, 30));

        inicio.setBackground(new java.awt.Color(0, 102, 102));
        inicio.setText("Volver al inicio");
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMouseClicked(evt);
            }
        });
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, 40));

        pagar.setBackground(new java.awt.Color(0, 153, 153));
        pagar.setText("Efectuar Pago");
        pagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagarMouseClicked(evt);
            }
        });
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });
        getContentPane().add(pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 110, 30));

        inst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i.jpg"))); // NOI18N
        inst.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                instStateChanged(evt);
            }
        });
        getContentPane().add(inst, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 90, 70, 70));

        fb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/f.jpg"))); // NOI18N
        getContentPane().add(fb, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, 70, 70));

        tw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t.jpg"))); // NOI18N
        getContentPane().add(tw, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 70, 70));

        bienvfin.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        bienvfin.setForeground(new java.awt.Color(0, 204, 204));
        bienvfin.setText("Ingrese los siguientes datos para continuar con su reservación. ");
        getContentPane().add(bienvfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 860, 30));

        targeta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        targeta.setForeground(new java.awt.Color(204, 51, 0));
        targeta.setText("Numero de targeta:");
        getContentPane().add(targeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cliente.setForeground(new java.awt.Color(204, 51, 0));
        cliente.setText("titular_targeta:");
        getContentPane().add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        fecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fecha.setForeground(new java.awt.Color(204, 51, 0));
        fecha.setText("Fecha de vencimiento:");
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));
        getContentPane().add(numTargeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 140, -1));
        getContentPane().add(titularTargeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 140, -1));
        getContentPane().add(fechaVence, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 140, -1));

        volver.setBackground(new java.awt.Color(0, 153, 153));
        volver.setText("volver");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 80, 30));
        getContentPane().add(guardaIdEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 60, -1));
        getContentPane().add(guardaIdAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 60, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Targeta de debito", " " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 140, -1));
        getContentPane().add(codigoSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 140, -1));

        codigoReserva.setEditable(false);
        getContentPane().add(codigoReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 140, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("Codigo de seguridad:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backGround.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 1370, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void instStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_instStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_instStateChanged

    private void pagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagarMouseClicked
       
    }//GEN-LAST:event_pagarMouseClicked

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
       
    }//GEN-LAST:event_volverMouseClicked

    private void inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseClicked
    
    }//GEN-LAST:event_inicioMouseClicked

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
       //boton que nos regresa a la ventana anterior en caso de que no se concluya la reservacion 
       ReservaAlojamiento Reservacion = new ReservaAlojamiento();
       Reservacion.setVisible(true);
       //manda a la ventana anterior el id del alojamiento para no perdelo y regresar a ver la informacion
       Reservacion.guardaIdAl.setText(guardaIdAl.getText());
       this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
       //boton para salir del proceso de reservacion e ir directo al inicio
       BusquedaAlojamiento index = new BusquedaAlojamiento();
       index.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_inicioActionPerformed

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        //genera un codigo aleatorio para la reservacion
        Random random = new Random();
        String code=new BigInteger(50, random).toString(32);
        //System.out.println("Random String " +code);
        codigoReserva.setText(code);
        try{
            BaseDeDatosConexion objCon=new BaseDeDatosConexion();
            Connection conn=objCon.getConection();  
            //consulta sql que inserta en la tabla reservacion los datos de pago, esto para simular un deposito que genera la reservacion
            ps=conn.prepareStatement("INSERT INTO reservacion(al_id,est_id,numero_targeta,titular_targeta,fecha_vencimiento,codigo_seguridad,codigo_reservacion) VALUES(?,?,?,?,?,?,?)"); 
            //guarda en la base de datos los datos ingresados en los jtextfiel para la reservacion 
            ps.setString(1,guardaIdAl.getText());
            ps.setString(2,guardaIdEst.getText());
            ps.setString(3,numTargeta.getText());
            ps.setString(4,titularTargeta.getText());
            ps.setString(5,fechaVence.getText());
            ps.setString(6,codigoSeguridad.getText());      
            ps.setString(7,codigoReserva.getText());
            int res=ps.executeUpdate();
            if(res>0){
                //En caso de que los datos sean correctos se realiza el pago y se hace la reservacion
                JOptionPane.showMessageDialog(null, "Pago realizado");
                JOptionPane.showMessageDialog(null, "Reservacion exitosa");       
                codigoEst(); //metodo que envia el codigo de reservacion al estudiante 
                //Cambia el estado del alojamiento de disponible a no disponible
                cambiaEstado();
                //una vez hecha la reservacion lleva a la ventana estudiante donde puede ver su codigo de reservacion    
                Estudiante est = new Estudiante();
                est.setVisible(true);
                //envia id_estudiante para que se haga la consulta y se muestre el codigo de reservacion
                est.txtId.setText(guardaIdEst.getText());
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Error al guardar datos");
            }
            conn.close();
        }
        catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente y/o completos");
        } 
    }//GEN-LAST:event_pagarActionPerformed

     public void codigoEst(){
            try{
            BaseDeDatosConexion objCon=new BaseDeDatosConexion();
            Connection conn=objCon.getConection(); 
            //Consulta sql que inserta en la tabla estudiante el codigo de reservacion generado anteriormente
            ps=conn.prepareStatement("UPDATE estudiante SET codigo=? WHERE id_estudiante=?"); 
            ps.setString(1,codigoReserva.getText());
            ps.setString(2,guardaIdEst.getText());
            int res=ps.executeUpdate();
            if(res>0){
            }else{
                JOptionPane.showMessageDialog(null, "Error al guardar codigo");
            }
        }catch (SQLException ex) {
            Logger.getLogger(FinalizarReservaPago.class.getName()).log(Level.SEVERE, null, ex);
        } 
     }    
     
      public void cambiaEstado(){
            try{
            BaseDeDatosConexion objCon=new BaseDeDatosConexion();
            Connection conn=objCon.getConection(); 
            //consulta sql que modifica la disponibilidad del alojamiento
            //para que una vez hecha la reservacion ya no aparezca como disponible
            ps=conn.prepareStatement("UPDATE alojamiento SET disponibilidad=? WHERE id_alojamiento=?"); 
            ps.setString(1,"no");
            ps.setString(2,guardaIdAl.getText());
            int res=ps.executeUpdate();
            if(res>0){
            }else{
                JOptionPane.showMessageDialog(null, "Error en la consulta");
            }
        }catch (SQLException ex) {
            Logger.getLogger(FinalizarReservaPago.class.getName()).log(Level.SEVERE, null, ex);
        } 
     } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarReservaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarReservaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarReservaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarReservaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalizarReservaPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvfin;
    private javax.swing.JLabel cliente;
    private javax.swing.JTextField codigoReserva;
    private javax.swing.JTextField codigoSeguridad;
    private javax.swing.JButton fb;
    private javax.swing.JLabel fecha;
    private javax.swing.JTextField fechaVence;
    private javax.swing.JLabel fondo;
    public javax.swing.JTextField guardaIdAl;
    public javax.swing.JTextField guardaIdEst;
    private javax.swing.JButton inicio;
    private javax.swing.JButton inst;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField numTargeta;
    private javax.swing.JButton pagar;
    private javax.swing.JLabel targeta;
    private javax.swing.JTextField titularTargeta;
    private javax.swing.JButton tw;
    private javax.swing.JTextField unirenta;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
