/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import conexion.BaseDeDatosConexion;
/**
 *
 * @author 52953
 */
public class IniciarSesionArr extends javax.swing.JFrame {

    
    //conexion a la base de datos
    PreparedStatement ps=null;
    ResultSet rs=null;
    BaseDeDatosConexion con=new BaseDeDatosConexion();
    Connection conn=con.getConection();
    
    public IniciarSesionArr() {
        initComponents();
        //vuelve invisible un jtextfield que guarda el id de un arrendador
        txtIdIS.setVisible(false);
    }
    
        private void limpiar(){
            //Limia los campos despues de iniciar sesion o si hubo algun error
            txtUsuario.setText(null);
            txtContra.setText(null);
        }
    
     public Image getIconImage(){
        //logotipo de la app
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo2.jpg"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        unirenta = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();
        bienvIS = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        usuario = new javax.swing.JLabel();
        pasword = new javax.swing.JLabel();
        tw = new javax.swing.JButton();
        fb = new javax.swing.JButton();
        inst = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        txtIdIS = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo2.jpg"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, -1));

        unirenta.setEditable(false);
        unirenta.setBackground(new java.awt.Color(102, 204, 0));
        unirenta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        unirenta.setText("    UNIRENTA");
        getContentPane().add(unirenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, 30));

        enviar.setBackground(new java.awt.Color(0, 153, 153));
        enviar.setText("Iniciar Sesion");
        enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarMouseClicked(evt);
            }
        });
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 110, 30));

        bienvIS.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        bienvIS.setForeground(new java.awt.Color(0, 204, 204));
        bienvIS.setText("Bienvenido arrendador, Ingrese sus datos para iniciar sesion.");
        getContentPane().add(bienvIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 800, 40));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 150, 30));
        getContentPane().add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 150, 30));

        usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(204, 51, 0));
        usuario.setText("Usuario:");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 80, -1));

        pasword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pasword.setForeground(new java.awt.Color(204, 51, 0));
        pasword.setText("Contraseña:");
        getContentPane().add(pasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 100, 20));

        tw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t.jpg"))); // NOI18N
        getContentPane().add(tw, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 70, 70));

        fb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/f.jpg"))); // NOI18N
        getContentPane().add(fb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, 70, 70));

        inst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i.jpg"))); // NOI18N
        getContentPane().add(inst, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 70, 70));

        volver.setBackground(new java.awt.Color(0, 153, 153));
        volver.setText("Volver");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 70, 30));

        txtIdIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdISActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 70, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backGround.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked

    }//GEN-LAST:event_volverMouseClicked

    private void enviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarMouseClicked
      
    }//GEN-LAST:event_enviarMouseClicked

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
       //guarda en una variable string la contraseña ingresada en el jtextfield 
       String pas=new String(txtContra.getPassword());
       //Llama a la funcion que hace la consulta  para ver si el arrendador existe
       //llama a un metodo que verifica que el usuario exista
       int id=login(txtUsuario.getText(),pas); 
       // String Cad= String.valueOf(id);
       if(id!=0){
        //Si el metodo anterior verifica que existe el usuario nos manda a la siguiente ventana (menu arrendador)   
        MenuArrendador menuarr = new MenuArrendador();
        menuarr.setVisible(true);
        //Se envia un dato a textfield que esta en MenuArrendador de txtIdIs
        menuarr.recibeIdArr.setText(txtIdIS.getText());
        //ps.setInt(1,ide);        
        this.dispose();
       }
    }//GEN-LAST:event_enviarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
       //Nos regresa a la ventana anterior (menu iniciar sesion)
       MenuIS mis = new MenuIS();
       mis.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void txtIdISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdISActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesionArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesionArr().setVisible(true);
            }
        });
    }
    //metodo que verifica que el usuario y contraseña ingresados sean corrctos
    public int login(String user, String pass){
        Integer result=0,id;
        MenuArrendador menu = new MenuArrendador();
         
        try{
            Statement ejecutor=conn.createStatement();
            //Consulta sql que selecciona correo y contraseña del arrendador para poder iniciar sesion
            ResultSet rs=ejecutor.executeQuery("SELECT * FROM arrendador WHERE correo='"+user+"' AND contra='"+pass+"'");
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Bienvenido");
                txtIdIS.setText(rs.getString("id_arrendador"));  //Guarda id arrendador en txtId 
                //Si es correcto regresa un 1
                result=1;
            }else{
                //Si no es correctto envia alerta y retorna un 0
                JOptionPane.showMessageDialog(null,"Problemas con el usuario y/o contraseña");
                result=0;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al conectar"+e.getMessage(),e.getMessage(),JOptionPane.ERROR_MESSAGE);
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvIS;
    private javax.swing.JButton enviar;
    private javax.swing.JButton fb;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton inst;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel pasword;
    private javax.swing.JButton tw;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtIdIS;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField unirenta;
    private javax.swing.JLabel usuario;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
