/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import conexion.BaseDeDatosConexion;

/**
 *
 * @author 52953
 */
public class MenuArrendador extends javax.swing.JFrame {
    //Conexion a la base de datos
    PreparedStatement ps=null;
    ResultSet rs=null;
    BaseDeDatosConexion con=new BaseDeDatosConexion();
    Connection conn=con.getConection();     
    
    public MenuArrendador() {
        initComponents();
        //oculta jtextfield que guarda el id del arrendador
        recibeIdArr.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tw = new javax.swing.JButton();
        fb = new javax.swing.JButton();
        insta = new javax.swing.JButton();
        listarAlojamientos = new javax.swing.JButton();
        cambiosUser = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        recibeIdArr = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Bienvenido,Seleccione la accion que desea realizar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 720, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo2.jpg"))); // NOI18N
        logo.setText("jLabel1");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 150, 140));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 204, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setText("     UNIRENTA");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 150, 30));

        tw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t.jpg"))); // NOI18N
        getContentPane().add(tw, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, 70, 70));

        fb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/f.jpg"))); // NOI18N
        getContentPane().add(fb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 120, 70, 70));

        insta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i.jpg"))); // NOI18N
        getContentPane().add(insta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 120, 70, 70));

        listarAlojamientos.setBackground(new java.awt.Color(0, 204, 204));
        listarAlojamientos.setText("Datos de alojamientos");
        listarAlojamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarAlojamientosActionPerformed(evt);
            }
        });
        getContentPane().add(listarAlojamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 220, 30));

        cambiosUser.setBackground(new java.awt.Color(0, 204, 204));
        cambiosUser.setText("Datos de usuario");
        cambiosUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiosUserActionPerformed(evt);
            }
        });
        getContentPane().add(cambiosUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 190, 30));

        cerrarSesion.setBackground(new java.awt.Color(0, 204, 204));
        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseClicked(evt);
            }
        });
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 120, 30));

        recibeIdArr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recibeIdArrActionPerformed(evt);
            }
        });
        getContentPane().add(recibeIdArr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 90, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backGround.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void listarAlojamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarAlojamientosActionPerformed
       //boton que nos manda a la ventada CRUD alojamiento 
       CRUDAlojamiento la = new CRUDAlojamiento();
       //Envia el id del arrendador que sera utilizado en la siguiente ventana
       la.recibeIdArr2.setText(recibeIdArr.getText());
       la.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_listarAlojamientosActionPerformed

    private void cambiosUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiosUserActionPerformed
       //boton que nos manda al formulario arrendador con operaciones eliminar,modificar y mostrar datos
       Arrendador arr = new Arrendador();
       arr.txtId.setText(recibeIdArr.getText());
       arr.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_cambiosUserActionPerformed

    private void cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseClicked

    }//GEN-LAST:event_cerrarSesionMouseClicked

    private void recibeIdArrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recibeIdArrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recibeIdArrActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
       //boton que nos manda a ventana de inicio de sesion tras cerrar una sesion
       IniciarSesionArr isArr = new IniciarSesionArr();
       isArr.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_cerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuArrendador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuArrendador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuArrendador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuArrendador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuArrendador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiosUser;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton fb;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton insta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton listarAlojamientos;
    private javax.swing.JLabel logo;
    public javax.swing.JTextField recibeIdArr;
    private javax.swing.JButton tw;
    // End of variables declaration//GEN-END:variables
}
